// The public address (WP67): a Cloudflare Pages project serves the built screens itself and hands only
// the Worker routes to the existing Worker through a service binding. deploy.yml runs this script; no
// network, no dependencies beyond wrangler's config reader.
//
//   node scripts/pages-out.mjs --assets dist/client --out <dir> --config wrangler.jsonc --project zhstrade
//     <dir>/out          a copy of the built screens without _redirects, _headers or 404.html (without a
//                        404.html, Pages answers unknown paths with index.html: the single-page app),
//                        plus _worker.js, which hands each request it gets to the Worker (binding APP),
//                        and _routes.json, which sends only the Worker routes (the Worker's
//                        assets.run_worker_first, default /api/*) to _worker.js.
//     <dir>/wrangler.json the Pages config: the APP service binding to the Worker and the Worker's
//                        compatibility_date. `wrangler pages deploy` run inside <dir> applies it.
//   node scripts/pages-out.mjs --redirect <assets dir> --to <https URL>
//     <assets dir>/_redirects  '/* <URL>/:splat 301': every screen path of the old address moves to the new
//                        one. Workers never apply _redirects to the routes the Worker runs first, so the
//                        API keeps answering at the old address too.
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// The binding name the generated _worker.js reads (and tests/verify-pages-out.mjs checks).
export const BINDING = 'APP';
// Shown only while the binding is missing (a project set up by hand without it); the site's own 503 line.
export const UNAVAILABLE = '서버 연결이 원활하지 않습니다. 잠시 후 다시 시도해 주세요.';
// Files Pages would treat as its own settings: the Worker's redirect would send the new address to
// itself, and any 404.html turns off the single-page fallback.
const PAGES_SETTINGS_FILES = new Set(['_redirects', '_headers', '404.html']);
const PROJECT_NAME = /^[a-z0-9](?:[a-z0-9-]{0,56}[a-z0-9])?$/;

export const WORKER_JS = `// Generated by scripts/pages-out.mjs. Pages runs this only for the Worker routes in _routes.json and hands
// the original request (address, cookies, Origin, CF-Connecting-IP) to the Worker through the ${BINDING} binding.
export default {
    fetch(request, env) {
        if (env && env.${BINDING}) return env.${BINDING}.fetch(request);
        return new Response(JSON.stringify({ error: ${JSON.stringify(UNAVAILABLE)} }), {
            status: 503,
            headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' },
        });
    },
};
`;

function fail(message) {
    console.error('pages-out: ' + message);
    process.exit(1);
}

function parseArgs(argv) {
    const args = {};
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (!a.startsWith('--')) fail(`unexpected argument ${a}`);
        const eq = a.indexOf('=');
        if (eq > 0) { args[a.slice(2, eq)] = a.slice(eq + 1); continue; }
        const next = argv[i + 1];
        if (next === undefined || next.startsWith('--')) fail(`${a} needs a value`);
        args[a.slice(2)] = next;
        i++;
    }
    return args;
}

// _routes.json from the Worker's assets.run_worker_first: true is every path, a list keeps its
// patterns ('!' patterns, which Workers serve as assets, become excludes), and nothing set is /api/*.
export function routesFor(runWorkerFirst) {
    if (runWorkerFirst === true) return { version: 1, include: ['/*'], exclude: [] };
    const list = Array.isArray(runWorkerFirst) && runWorkerFirst.length ? runWorkerFirst : ['/api/*'];
    if (!list.every(r => typeof r === 'string' && /^!?\//.test(r))) throw new Error('assets.run_worker_first patterns must start with /');
    const include = list.filter(r => !r.startsWith('!')), exclude = list.filter(r => r.startsWith('!')).map(r => r.slice(1));
    if (!include.length) throw new Error('assets.run_worker_first has no Worker route');
    if (include.length + exclude.length > 100) throw new Error('Pages allows at most 100 routes');
    return { version: 1, include, exclude };
}

// Every file or folder below `dir` whose name is in `names`.
function findNamed(dir, names, found = []) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (names.has(entry.name)) found.push(full);
        else if (entry.isDirectory()) findNamed(full, names, found);
    }
    return found;
}

function buildPagesFolder(args) {
    const assets = path.resolve(args.assets || fail('--assets is required'));
    const dir = path.resolve(args.out || fail('--out is required'));
    const configPath = path.resolve(args.config || 'wrangler.jsonc');
    const project = args.project || 'zhstrade';
    if (!PROJECT_NAME.test(project)) fail(`--project ${project}: lowercase letters, digits and dashes, at most 58`);
    if (!existsSync(path.join(assets, 'index.html'))) fail(`${assets} has no index.html (run pnpm build first)`);
    const inside = (child, parent) => { const r = path.relative(parent, child); return r === '' || (!r.startsWith('..') && !path.isAbsolute(r)); };
    if (inside(dir, assets) || inside(assets, dir)) fail('--out must be outside the assets folder and must not contain it');
    if (!existsSync(configPath)) fail(`${configPath} not found`);
    // <dir>/wrangler.json is replaced on every run, so only a Pages config this script wrote may be there.
    const ownConfig = path.join(dir, 'wrangler.json');
    if (existsSync(ownConfig)) {
        let previous = null;
        try { previous = JSON.parse(readFileSync(ownConfig, 'utf8')); } catch { /* not ours */ }
        if (previous?.pages_build_output_dir !== './out') fail(`${ownConfig} exists and is not a Pages config from this script`);
    }

    const require = createRequire(import.meta.url);
    const { experimental_readRawConfig } = require('wrangler');
    const { rawConfig } = experimental_readRawConfig({ config: configPath });
    const worker = rawConfig.name, date = rawConfig.compatibility_date;
    if (typeof worker !== 'string' || !worker) fail(`${configPath} has no Worker name`);
    if (typeof date !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(date)) fail(`${configPath} has no compatibility_date`);
    let routes;
    try { routes = routesFor(rawConfig.assets?.run_worker_first); } catch (e) { fail(e.message); }

    // Only the files this script owns are replaced, so a second run leaves no stale screens behind.
    const out = path.join(dir, 'out');
    mkdirSync(dir, { recursive: true });
    rmSync(out, { recursive: true, force: true });
    cpSync(assets, out, { recursive: true });
    const dropped = findNamed(out, PAGES_SETTINGS_FILES);
    for (const f of dropped) rmSync(f, { recursive: true, force: true });
    writeFileSync(path.join(out, '_worker.js'), WORKER_JS);
    writeFileSync(path.join(out, '_routes.json'), JSON.stringify(routes, null, 2) + '\n');
    const pagesConfig = {
        name: project,
        pages_build_output_dir: './out',
        compatibility_date: date,
        services: [{ binding: BINDING, service: worker }],
    };
    writeFileSync(ownConfig, JSON.stringify(pagesConfig, null, 2) + '\n');
    const files = readdirSync(out, { recursive: true }).filter(f => statSync(path.join(out, f)).isFile()).length;
    console.log(`pages-out: ${path.relative(process.cwd(), out) || out} (${files} files${dropped.length ? `, left out ${dropped.map(f => path.relative(out, f)).join(', ')}` : ''}), Worker routes ${routes.include.join(' ')}${routes.exclude.length ? ` except ${routes.exclude.join(' ')}` : ''}, binding ${BINDING} to ${worker}, project ${project}`);
}

function writeRedirect(args) {
    const dir = path.resolve(args.redirect);
    if (!existsSync(path.join(dir, 'index.html'))) fail(`${dir} has no index.html (run pnpm build first)`);
    let to;
    try { to = new URL(args.to || fail('--to is required')); } catch { fail(`--to ${args.to} is not a URL`); }
    // Workers accept only relative or https:// redirect targets (and no port), so anything else is refused
    // here rather than silently dropped by the deploy.
    if (to.protocol !== 'https:' || to.port) fail('--to must be an https address without a port');
    if (to.pathname !== '/' || to.search || to.hash || to.username || to.password) fail('--to must be an address without a path');
    const line = `/* ${to.origin}/:splat 301\n`;
    writeFileSync(path.join(dir, '_redirects'), line);
    console.log(`pages-out: ${path.join(path.relative(process.cwd(), dir) || '.', '_redirects')}: ${line.trim()}`);
}

// Run as a script (tests/verify-pages-out.mjs imports the exports above without running it).
if (process.argv[1] && existsSync(process.argv[1]) && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
    const args = parseArgs(process.argv.slice(2));
    if (args.redirect !== undefined) writeRedirect(args);
    else buildPagesFolder(args);
}
